/*****************************************************************************
*
* Freescale Confidential Proprietary
*
* Copyright (c) 2014 Freescale Semiconductor;
* All Rights Reserved
*
*****************************************************************************
*
* THIS SOFTWARE IS PROVIDED BY FREESCALE "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL FREESCALE OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
****************************************************************************/
#ifndef MATCH_DESCRIPTORS_GRAPH_DEF_H
#define MATCH_DESCRIPTORS_GRAPH_DEF_H

// PI stands for Process Identifier
// GN stands for Graph Name
#include "stringify_macros.h"

#define MATCH_DESCRIPTORS_PI			APU_MATCH_DESCRIPTORS
#define MATCH_DESCRIPTORS_GN			XSTR(MATCH_DESCRIPTORS_PI)

#define MATCH_DESCR_GR_IN0		"INPUT_0"
#define MATCH_DESCR_GR_IN1		"INPUT_1"
#define MATCH_DESCR_GR_OUT0		"OUTPUT_0"
#define MATCH_DESCR_GR_OUT1		"OUTPUT_1"


#define MATCH_DESCR_GR_CFG		"INPUT_CONFIG"
#define MATCH_DESCR_GR_MARK	"MARK_COLOR_CHANNEL"

#endif
