/*****************************************************************************
*
* Freescale Confidential Proprietary
*
* Copyright (c) 2014 Freescale Semiconductor;
* All Rights Reserved
*
*****************************************************************************
*
* THIS SOFTWARE IS PROVIDED BY FREESCALE "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL FREESCALE OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
****************************************************************************/

#ifndef _ACF_AUTOKERNELINC_HPP
#define _ACF_AUTOKERNELINC_HPP

#include <stdint.h>

extern int16_t gsACF_FIRST_TILE_FLAG;
extern int16_t gsACF_LAST_TILE_FLAG;
extern int16_t gsACF_TILE_WIDTH_IN_CHUNKS;
extern int16_t gsACF_FIRST_CUID;

typedef enum
{
   ACF_VAR_FIRST_TILE_FLAG,
   ACF_VAR_LAST_TILE_FLAG,
   ACF_VAR_TILE_WIDTH_IN_CHUNKS,
   ACF_VAR_FIRST_CUID
} ACF_VAR;

int16_t ACF_RET_VAR(ACF_VAR lVar);

void ACF_PUSH_VEC_BUFFER_TO_FIFO(kernel_io_desc lIoDescVecBuffer, vec16u lvVecBufferSize, kernel_io_desc lIoDescFifoSize);

#endif //_ACF_AUTOKERNELINC_HPP
