/*****************************************************************************
*
* Freescale Confidential Proprietary
*
* Copyright (c) 2014 Freescale Semiconductor;
* All Rights Reserved
*
*****************************************************************************
*
* THIS SOFTWARE IS PROVIDED BY FREESCALE "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL FREESCALE OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
****************************************************************************/
#ifndef APU_FACE_DETECTION_LBP_GRAPH_H
#define APU_FACE_DETECTION_LBP_GRAPH_H

#include "stringify_macros.h"

#define FACE_DETECTION_PI	APU_FACE_DETECTION_LBP
#define FACE_DETECTION_GN	XSTR(FACE_DETECTION_PI)

#define FACE_DETECTION_2_PI		APU_FACE_DETECTION_LBP_2
#define FACE_DETECTION_2_GN		XSTR(FACE_DETECTION_2_PI)

#define FACE_DETECTION_4_PI		APU_FACE_DETECTION_LBP_4
#define FACE_DETECTION_4_GN		XSTR(FACE_DETECTION_4_PI)


#define FACE_DETECTION_6_PI		APU_FACE_DETECTION_LBP_6
#define FACE_DETECTION_6_GN		XSTR(FACE_DETECTION_6_PI)


#define FACE_DETECTION_10_PI		APU_FACE_DETECTION_LBP_10
#define FACE_DETECTION_10_GN		XSTR(FACE_DETECTION_10_PI)

    //add graph ports
#define FACE_DET_GR_IN_IMG			"INPUT_IMAGE"
#define FACE_DET_GR_IN_CASC_SZ		"INPUT_CASCADE_SIZES_AND_SKIP"
#define FACE_DET_GR_IN_CASC_FEAT	"INPUT_CASCADE_FEATURES"
#define FACE_DET_GR_IN_CASC_STAGES	"INPUT_CASCADE_STAGES"
#define FACE_DET_GR_IN_PIX_SHFT		"INPUT_PIXEL_SHIFTS"
#define FACE_DET_GR_IN_PIX_OFFS		"INPUT_PIXEL_OFFSETS"
#define FACE_DET_GR_OUT				"OUTPUT"
#define FACE_DET_GR_OUT_INTEGR_IMG	"OUTPUT_INTEGRAL_IMAGE"

#endif