/*****************************************************************************
*
* Freescale Confidential Proprietary
*
* Copyright (c) 2014 Freescale Semiconductor;
* All Rights Reserved
*
*****************************************************************************
*
* THIS SOFTWARE IS PROVIDED BY FREESCALE "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL FREESCALE OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
****************************************************************************/
#ifndef APU_CONVOLUTION_GRAPH_H
#define APU_CONVOLUTION_GRAPH_H

#include <stringify_macros.h>

#define CONVOLUTION_PI					APU_CONVOLUTION
#define CONVOLUTION_GN					XSTR(CONVOLUTION_PI) //"APU_CONVOLUTION"

#define CONVOLUTION_GRAPH_IN			"ConvGraph_Input"
#define CONVOLUTION_GRAPH_OUT			"ConvGraph_Output"
#define CONVOLUTION_GRAPH_IN_FILTER		"ConvGraph_In_Filt"

#define CONVOLUTION_GRAPH_FILTER_WIDTH	"ConvGraph_FiltWidth"
#define CONVOLUTION_GRAPH_FILTER_HEIGHT	"ConvGraph_FiltHeight"
#define CONVOLUTION_GRAPH_FILTER_SCALE	"ConvGraph_FiltScale"
#define CONVOLUTION_GRAPH_FILTER_SYMMFLG "ConvGraph_FiltSymmFlag"

#endif

