/* This file was automatically generated by the MULTI Project Manager  */

/* Define/export a built-in MRDisk based on the static.iso image that was
 * pulled into the file system AddressSpace via -rawimport into the section
 * .staticdisk.  We use the toolchain-provided symbols for the beginning
 * and size of the section.  See the toolchain documentation for a
 * thorough explanation of these features.
 */

#include <INTEGRITY.h>
#include <stdlib.h>
#include <filesystem/fsmrdisk.h>



extern char __ghsbegin_staticdisk[], __ghssize_staticdisk[];

FSMRDisk __ghsentry_fs_mrdisk_staticdisk = {
	"staticdisk", /* The file system will know the disk by this name */
	__ghsbegin_staticdisk,
	(size_t)__ghssize_staticdisk
};

/* path to raw image file:
$__VISION_S32V234_SDK/os/integrity/arm64/gdi_kernel/multi/proj/static.iso
*/
