#!bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
#mount -t debugfs debug /proc/sys/debug
#mount -t tmpfs none /dev


cat /proc/tty/driver/ttyAMA

#mknod -m 622 /dev/console c 5 1
#mknod -m 666 /dev/null c 1 3
#mknod -m 666 /dev/zero c 1 5

#/sbin/mdev -s

#cat /proc/interrupts
#cat /proc/stat

